# Generated by Django 3.2.18 on 2023-02-17 20:20

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Children', 'Children'), ('Elderly', 'Elderly'), ('Environmental', 'Environmental'), ('Education', 'Education')], max_length=20)),
                ('location', models.CharField(max_length=60, unique=True)),
                ('geo_extend', models.CharField(choices=[('Local', 'Local'), ('Regional', 'Regional'), ('Multiregional', 'Multiregional'), ('National', 'National'), ('International', 'International')], max_length=20)),
                ('description', djrichtextfield.models.RichTextField()),
                ('phone', models.IntegerField(max_length=13)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('description', djrichtextfield.models.RichTextField()),
                ('contact', models.CharField(max_length=60, unique=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='blog.ngo')),
            ],
        ),
    ]
