# Generated by Django 3.2.18 on 2023-02-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_ngo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='description',
            field=models.TextField(),
        ),
    ]
