# Generated by Django 3.2.18 on 2023-02-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_ngo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
