# Generated by Django 3.2.18 on 2023-02-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ngo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ngo_images/'),
        ),
    ]
